version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_mysql_username
      - MYSQL_PASSWORD=your_mysql_password
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=anchor
      - MYSQL_USER=root
      - MYSQL_PASSWORD=VANadium123!@#
      - MYSQL_ROOT_PASSWORD=VANadium123!@#
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

