# Generated by Django 4.1.7 on 2023-05-08 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(blank=True, null=True)),
                ('jobno', models.CharField(blank=True, max_length=30, null=True)),
                ('jobname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('auth_by', models.CharField(blank=True, max_length=30, null=True)),
                ('report_to', models.CharField(blank=True, max_length=30, null=True)),
                ('man1', models.CharField(blank=True, max_length=70, null=True)),
                ('man2', models.CharField(blank=True, max_length=70, null=True)),
                ('man3', models.CharField(blank=True, max_length=70, null=True)),
                ('model1', models.CharField(blank=True, max_length=70, null=True)),
                ('model2', models.CharField(blank=True, max_length=70, null=True)),
                ('model3', models.CharField(blank=True, max_length=70, null=True)),
                ('serial1', models.CharField(blank=True, max_length=70, null=True)),
                ('serial2', models.CharField(blank=True, max_length=70, null=True)),
                ('serial3', models.CharField(blank=True, max_length=70, null=True)),
                ('unit1', models.IntegerField(blank=True, null=True)),
                ('unit2', models.IntegerField(blank=True, null=True)),
                ('unit3', models.IntegerField(blank=True, null=True)),
                ('loc1', models.CharField(blank=True, max_length=70, null=True)),
                ('loc2', models.CharField(blank=True, max_length=70, null=True)),
                ('loc3', models.CharField(blank=True, max_length=70, null=True)),
                ('desc', models.TextField(blank=True, max_length=700, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, max_length=200, null=True)),
                ('complete', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
