# Generated by Django 4.1.7 on 2023-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigerant',
            name='qty',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
