# Generated by Django 4.1.7 on 2023-05-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_refrigerant_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='qty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
