# Generated by Django 4.1.7 on 2023-05-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_material_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cust_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tech_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
